Add Live Data to Reviews Panel
woocommerce/wc-admin pull request #1055
Opened 2018-12-10 20:35 UTC by justinshreve

Fixes #1036.

This PR hooks up the 'reviews' activity panel to live data.

It also modifies the `/products/*` and `/products/reviews/*` endpoints, by allowing embedding (https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding/) of some product fields when `?_embed=1` is present in the query string.

This allows us to get info like the product name, permalink, and image without extra requests. It also **matches the behavior** of WP-API Core endpoints. For example on a comment, you can receive some posts field. So this change makes things easier for us, and makes sense from a consistency point of view. (You could already embed some user info via the reviews endpoint).

### Screenshots

<img width="845" alt="screen shot 2018-12-10 at 1 25 49 pm" src="https://user-images.githubusercontent.com/689165/49759260-2836c100-fc8f-11e8-8072-5cc82bcf976c.png">

### Detailed test instructions:

- Click reviews on the activity panel
- Verify that your reviews properly load in

2018-12-11 07:08 UTC, joshuatf requested changes
Looking good and testing well!  Nice work on this @justinshreve 👍 

I've added a couple comments where I think we can reduce a bit of this code, but otherwise things are looking good to merge.

2 side notes that may be better suited for separate PRs:
1. Should we add testing for the API response?
2. Products without an image that use the placeholder image look like misaligned images (since the background is white).  Do we need to make any changes here or do they look good to as is @LevinMedia ?

<img width="260" alt="screen shot 2018-12-11 at 3 07 14 pm" src="https://user-images.githubusercontent.com/10561050/49783928-84184d00-fd56-11e8-9fb4-6b3b29b2d3dd.png">

2018-12-11 07:08 UTC, joshuatf commented on client/header/activity-panel/panels/reviews.js
> +		const product = review._embedded.up[ 0 ];
Probably overly cautious, but do we want to check that these properties exist before rendering?

2018-12-11 15:24 UTC, justinshreve commented on includes/api/class-wc-admin-rest-products-controller.php
> +	public function get_item_schema() {
The difference was adding `embed` to the context field. But good call, I've simplified this and reduced a lot of lines.

2018-12-12 02:02 UTC, joshuatf approved these changes

2018-12-12 02:08 UTC, joshuatf commented
@justinshreve Woo- all that red!  Looks good and new tests are all passing.

I think we can address the placeholder image in a separate issue ( #1067 ) since it's a bit outside the scope of this PR.

LGTM!

2018-12-12 12:44 UTC, justinshreve commented
Thank you for logging that!

2018-12-12 13:35 UTC, merged