Activity Panel Outbound Link
woocommerce/wc-admin pull request #213
Opened 2018-07-16 16:09 UTC by justinshreve

This PR adds a new Activity Panel component for creating a styled outbound link as [seen here](https://automattic.invisionapp.com/d/main#/console/14654690/304742001/inspect).

Closes #194.

It also does some README cleanup/adds a README for the `Link` component, and renames the `<Link>` `to` prop to `href` which feels a bit more natural for this wrapper component.

<img width="521" alt="screen shot 2018-07-16 at 11 56 39 am" src="https://user-images.githubusercontent.com/689165/42769465-318b396a-88f0-11e8-837c-c695f91d9115.png">

<img width="523" alt="screen shot 2018-07-16 at 12 01 59 pm" src="https://user-images.githubusercontent.com/689165/42769471-346cabdc-88f0-11e8-8914-29c0b34e157e.png">

To Test:
* Open up the orders activity panel and scroll to the bottom. You should see an outbound link. Verify the various states and that the link clicks through to the orders page.

2018-07-16 19:22 UTC, ryelle requested changes
This works as described, tested with keyboard and VoiceOver too 👍  - I just have some comments around the code itself.

2018-07-16 19:22 UTC, ryelle commented on client/layout/activity-panel/activity-outbound-link/README.md
> +`ActivityPanelOutboundLink` creates a styled link for use in the Activity Panel.
You're using both `ActivityPanelOutboundLink` & `ActivityOutboundLink` here, but I think it should be just `ActivityOutboundLink`.

2018-07-16 19:22 UTC, ryelle commented on client/layout/activity-panel/style.scss
> +	padding-bottom: $gap-small * 6;
Can you add a comment for why this is needed?

2018-07-16 19:22 UTC, ryelle commented on client/layout/activity-panel/activity-outbound-link/index.js
> +		<Link href={ href } type={ type } className={ classes }>
Maybe allow for passing extra props through here, since `Link` will accept & pass on extra props to the `RouterLink` or `a` components.

2018-07-17 13:01 UTC, justinshreve commented
@ryelle Thanks for the review, and for the `$gap $gutter` trick too. I totally missed the responsive rule there. I've addressed all the feedback above.

2018-07-17 18:44 UTC, ryelle approved these changes
Looks good now! Thanks for the updates 🙂

2018-07-17 18:51 UTC, merged