Deactivate plugin if dependencies not met
woocommerce/wc-admin pull request #530
Opened 2018-10-15 18:51 UTC by joshuatf

Tables are installed on the hook `woocommerce_install_get_tables` which doesn't get refired if WooCommerce is not activated on initial wc-admin plugin activation.

This PR prevents the plugin from being activated if dependencies are not also activated.

Fixes #528 

### Bug replication

1.  On a fresh install (or remove all wc-admin related tables) install and activate wc-admin.
2.  Install and activate WooCommerce.
3.  Visit Revenue page and you should see the following error since tables were never created.

<img width="1516" alt="revenue_error" src="https://user-images.githubusercontent.com/10561050/46971269-86796600-d089-11e8-8a93-7a72df399449.png">

### Detailed test instructions:

1.  Install and attempt to activate wc-admin without WooCommerce or Gutenberg installed.
2.  Plugin notice should still read `The WooCommerce Admin feature plugin requires both Gutenberg and WooCommerce to be installed and active.`
3.  Plugin should be deactivated.

2018-10-15 19:41 UTC, allendav commented
This works, but the UX could be confusing, since you will still see the "plugin activated" notice even when activation is "blocked" this way, i.e.:

<img width="1232" alt="screen shot 2018-10-15 at 12 38 39 pm" src="https://user-images.githubusercontent.com/1595739/46973901-693b9c00-d077-11e8-95f3-fdd9c57f9232.png">

Maybe unset the activate param to avoid that, e.g.:

```
function deactivate_wc_admin_plugin() {
	if ( ! dependencies_satisfied() ) {
		deactivate_plugins( plugin_basename( WC_ADMIN_PLUGIN_FILE ) );
		unset( $_GET['activate'] );
	}
}
add_action( 'admin_init', 'deactivate_wc_admin_plugin' );
```

2018-10-15 19:44 UTC, allendav requested changes
Added comment about trying to avoid confusing "activated" message when plugin fails to find its dependencies.

2018-10-17 12:45 UTC, joshuatf commented
@allendav Great idea; thanks!  Added that in.

2018-10-18 17:21 UTC, belcherj approved these changes
LGTM if @allendav agrees.

2018-10-18 18:35 UTC, allendav approved these changes
Perfect. :shipit:

2018-10-18 18:37 UTC, merged