Add navigation feedback notes
woocommerce/wc-admin pull request #5475
Opened 2020-10-26 21:10 UTC by joshuatf

Fixes #5334

Adds notes for navigation feedback.

### Screenshots
<img width="539" alt="Screen Shot 2020-10-26 at 5 07 50 PM" src="https://user-images.githubusercontent.com/10561050/97228801-cbbeeb00-17ad-11eb-964e-00ab2fc5ef2e.png">

### Detailed test instructions:

1. With the navigation feature disabled, trigger the `wc_admin_daily` cron event.
1. Make sure no note is created.
1. Enable the navigation feature.
1. Trigger `wc_admin_daily`.
1. Check that the first feedback note is created.
1. After 5 days of creating the first note (or speed things up by changing the first note's date back in time), trigger `wc_admin_daily`.
1. Check that the second feedback note is created.

2020-10-27 18:42 UTC, jeffstieler requested changes
This tested well, and the code looks good save for some class name issues.

2020-10-27 18:42 UTC, jeffstieler commented on src/Notes/NavigationFeedback.php
> +class Navigation_Feedback {
The classnames should match the file names for the upcoming Jetpack Autoloader update.

2020-10-27 18:42 UTC, jeffstieler commented on src/Notes/NavigationFeedbackFollowUp.php
> +class Navigation_Feedback_Follow_Up {
The classnames should match the file names for the upcoming Jetpack Autoloader update.

2020-10-27 18:42 UTC, jeffstieler commented on src/Notes/NavigationFeedback.php
> +class Navigation_Feedback {
```suggestion
class NavigationFeedback {
```

2020-10-27 18:42 UTC, jeffstieler commented on src/Events.php
> +use \Automattic\WooCommerce\Admin\Notes\Navigation_Feedback;
```suggestion
use \Automattic\WooCommerce\Admin\Notes\NavigationFeedback;
```

2020-10-27 18:42 UTC, jeffstieler commented on src/Events.php
> +use \Automattic\WooCommerce\Admin\Notes\Navigation_Feedback_Follow_Up;
```suggestion
use \Automattic\WooCommerce\Admin\Notes\NavigationFeedbackFollowUp;
```

2020-10-27 18:42 UTC, jeffstieler commented on src/Events.php
> +		Navigation_Feedback::possibly_add_note();
```suggestion
		NavigationFeedback::possibly_add_note();
```

2020-10-27 18:42 UTC, jeffstieler commented on src/Events.php
> +		Navigation_Feedback_Follow_Up::possibly_add_note();
```suggestion
		NavigationFeedbackFollowUp::possibly_add_note();
```

2020-10-28 13:41 UTC, joshuatf commented
Thanks for the heads up, @jeffstieler- updated in https://github.com/woocommerce/woocommerce-admin/pull/5475/commits/f69a9019671a677c15945c5e180094f33b3ae59c

Is there an open issue to update all the other class names for the Jetpack autoloader update?

2020-10-28 13:49 UTC, jeffstieler commented
> Is there an open issue to update all the other class names for the Jetpack autoloader update?

Yes, that's been rolled into https://github.com/woocommerce/woocommerce-admin/pull/5462

2020-10-28 17:23 UTC, jeffstieler approved these changes
Looks good 👍 

Rebasing against the latest `main` should fix the build. Then 🚢  it!

2020-10-29 20:30 UTC, merged