Hook Reference: Automate a reference resource
woocommerce/wc-admin pull request #6454
Opened 2021-02-26 02:40 UTC by psealock

Fixes https://github.com/woocommerce/woocommerce-admin/issues/2924

### Detailed test instructions:

```
node ./bin/hook-reference.js
```

2021-03-02 07:58 UTC, ilyasfoo commented
@psealock I've tested running `npm run create-hook-reference` with node v12.21.0, and it gives the following error:
```
Error: Cannot find module 'fs/promises'
Require stack:
- .../plugins/woocommerce-admin/bin/hook-reference/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (.../plugins/woocommerce-admin/bin/hook-reference/index.js:2:38)
```

I suspected this was because `fs/promises` alias [is not in v12](https://github.com/nodejs/node/issues/35740#issuecomment-713778857). I've tested to change `require( 'fs/promises' );` to `require( 'fs' ).promises` and it works well with both v12 and v14.

Not a hard requirement, but would it be better to use the one that's supported by node v12 and above?

2021-03-03 20:28 UTC, loranallensmith commented
This is awesome @psealock!  :tada:  Thank you for putting it together.  I especially love the way the `sourceFile` URL links to the canonical URL _and_ highlights the lines in question.  🤩 


![Screen Shot 2021-03-03 at 3 27 50 PM](https://user-images.githubusercontent.com/3477155/109867920-0d1c4700-7c35-11eb-9157-855b1bae643d.png)

2021-03-09 21:45 UTC, joelclimbsthings commented on bin/hook-reference/index.js
> +async function getFilePaths( dir ) {
`Promise.all`, `map`, `reduce`, and _recursion_ all in a ~10 line async function. 👏🏻

2021-03-09 22:01 UTC, joelclimbsthings requested changes
❤️ this @psealock . Tested and works well.

Do we have any expectations on how the generated `json` will be utilized? Would it useful to integrate this script into any part of the ci/build/release process?

Totally optional, but I like it when a script gives _some_ kind of output to assure me that in executed correctly. Something like `Hook reference generated at ${path/file}`

2021-03-15 00:10 UTC, psealock commented
>Not a hard requirement, but would it be better to use the one that's supported by node v12 and above?

Good call and thanks for the tip. I fixed that in https://github.com/woocommerce/woocommerce-admin/pull/6454/commits/66b205c9706d23211d285373c503ae1b6fe59284

2021-03-15 00:47 UTC, psealock commented
Thanks for the review @joelclimbsthings 

>Totally optional, but I like it when a script gives some kind of output to assure me that in executed correctly. Something like Hook reference generated at ${path/file}

Great idea! I added some fancy logs in https://github.com/woocommerce/woocommerce-admin/pull/6454/commits/3f2354bba976e9d6f6ff08c15eec9a604e688233.

<img width="1162" alt="Screen Shot 2021-03-15 at 1 43 35 PM" src="https://user-images.githubusercontent.com/1922453/111090466-ad0e9480-8594-11eb-95e4-2704a9e60e32.png">

>Do we have any expectations on how the generated json will be utilized?

Since you can easily make a `GET` request to `.json` pages on Github, I think it would be used as an external resource loaded by what ever page we create to make these hooks viewable and searchable.

>Would it useful to integrate this script into any part of the ci/build/release process?

Eventually, I think so.

2021-03-15 19:44 UTC, joelclimbsthings commented
💯 Those are 🌶️ . 🚢

2021-03-15 19:44 UTC, joelclimbsthings approved these changes

2021-03-17 00:27 UTC, merged