Use wc filter to get status tabs for tools category
woocommerce/wc-admin pull request #6525
Opened 2021-03-05 14:41 UTC by joshuatf

Fixes #6524 

Uses the status filter to get registered tabs for the tools menu.

Note that this requires copying over the default tabs, but I don't think this is a worse solution than what we had since we were manually adding all these items anyway.

### Screenshots
<img width="283" alt="Screen Shot 2021-03-05 at 9 34 42 AM" src="https://user-images.githubusercontent.com/10561050/110130034-95662d80-7d96-11eb-9757-725e454d2e4e.png">

### Detailed test instructions:

1. Register a new tab via the filter.
```
add_filter( 'woocommerce_admin_status_tabs', function ( array $tabs ) {
	$tabs['my-tools-page'] = __( 'My Tools Page', 'your-text-domain' );
	return $tabs;
} );
```

2. Enable the new navigation.
3. Make sure the menu item for the registered tab is shown under `Tools`.

2021-03-05 14:49 UTC, frosso reviewed
FWIW - this is great, thanks!
Maybe in the future the `woocommerce_admin_status_tabs` can be deprecated in favor or a filter name that is more appropriate (since we're not adding tabs anymore)

2021-03-05 20:39 UTC, joelclimbsthings commented
Hey @joshuatf ! Good work. I did notice a couple oddities:

I'm showing an excess listing for "Status" under my extensions menu when activating this branch, which points to the System Status page. 

![image](https://user-images.githubusercontent.com/444632/110170894-b71fde80-7daf-11eb-8437-df3e12eb0566.png)


I'm _also_ still showing that listing under the Tools menu as expected, but I'm missing the "Import/Export" link (as compared to `main`):

This branch:
![image](https://user-images.githubusercontent.com/444632/110170813-99527980-7daf-11eb-9e3c-5b26374744e2.png)

On `main`: 
![image](https://user-images.githubusercontent.com/444632/110170944-cc950880-7daf-11eb-8cb3-ffb78cb70286.png)

2021-03-05 20:40 UTC, joelclimbsthings requested changes

2021-03-05 20:40 UTC, joelclimbsthings commented on TESTING-INSTRUCTIONS.md
> +1. Register a new tab via the filter.
:heart:

2021-03-09 13:24 UTC, joshuatf commented
Great catch on both fronts, @joelclimbsthings!

Pushed fixes in https://github.com/woocommerce/woocommerce-admin/pull/6525/commits/6cdf7577632a6952b2d525cf1f0d36d87bf4908d

2021-03-09 17:24 UTC, joelclimbsthings approved these changes
Great work! :ship:

2021-03-09 22:41 UTC, merged