Change "Store Setup" link in top bar to "Finish setup"
woocommerce/wc-admin pull request #6526
Opened 2021-03-05 16:39 UTC by elizaan36

This is a small tweak to the "Store setup" link in the top bar that only appears when the store setup task list isn't complete.

<img width="160" alt="Screen Shot 2021-03-05 at 10 06 35 AM" src="https://user-images.githubusercontent.com/5121465/110144879-75d30300-7d9e-11eb-85e6-c5b8c89a9e00.png">

Using a verb in "Finish setup" makes the link more actionable. Also, this update uses sentence case rather than title case.

Just a note that I also changed the tests but would be great if someone had a look to make sure everything there is still ok.

cc @pmcpinto

2021-03-07 23:47 UTC, samueljseay approved these changes
Looks good to me. Thanks for this! Assuming @pmcpinto is happy then 🚀

2021-03-07 23:48 UTC, samueljseay requested changes
Sorry I didn't check the e2e tests, It's likely this copy is used in those tests and thats why its failing.

2021-03-08 23:43 UTC, samueljseay commented
I'll take a look at fixing up the tests here.

2021-03-08 23:46 UTC, samueljseay approved these changes
🚀

2021-03-09 21:31 UTC, elizaan36 commented
Thanks Sam for taking a look. I shared with Pedro in Slack before I created the issue so we're gtg. Not sure how to fix the tests but let me know if there's anything I can do.

2021-03-09 22:49 UTC, joshuatf approved these changes
Nice tweak- thanks for this!

2021-03-09 22:50 UTC, merged