Updates default analytics menu
woocommerce/wc-admin pull request #658
Opened 2018-10-23 19:25 UTC by belcherj

Closes #624

- Removes Overview from the Analytics menu of the wp-admin
- Defaults Analytics menu to the Revenue report
- Makes Analytics link in breadcrumbs direct to the Revenue report

### Screenshots

![screen shot 2018-10-25 at 10 36 01 am](https://user-images.githubusercontent.com/6817400/47509226-a3f5bf00-d843-11e8-8392-3bbb668fcd3b.png)

### Detailed test instructions:

 - Click Analytics menu in the wp-admin
 - Do all the right menus open, close, highlight
 - Click around different reports
 - Do all the right menus open, close, highlight
 - Use breadcrumbs
 - Do all the right menus open, close, highlight
 - Does the Analytics link goto revenue report?

2018-10-25 16:48 UTC, timmyc requested changes
Looking pretty good, I did hit a few bugs while testing though. First up was if I directly opened up the products report, with some pre-set query filters, the Products menu item was not being highlighted:

![products analytics woo test woocommerce 2018-10-25 09-46-19](https://user-images.githubusercontent.com/22080/47516685-f67ead80-d83a-11e8-8d70-a8c6f99e4ead.png)

The second item I hit was when on the Revenue report, if I clicked "Analytics" in the breadcrumbs, the following was shown in my js console:

![image](https://user-images.githubusercontent.com/22080/47516740-19a95d00-d83b-11e8-9873-ce925980bae5.png)

2018-10-26 13:48 UTC, belcherj commented
If feel like the code to fix the warning is messier than leaving it.  Especially since we are logging out the warning:  https://github.com/woocommerce/wc-admin/blob/master/client/analytics/report/index.js#L65

@timmyc What you think?

2018-10-27 01:15 UTC, timmyc approved these changes

2018-10-27 01:15 UTC, timmyc commented
The highlight bug is indeed fixed up, and excellent point on the history item - lets get this merged in!

2018-10-27 17:38 UTC, merged