Docblock fixes in TimeInterval
woocommerce/wc-admin pull request #6585
Opened 2021-03-14 17:20 UTC by tivnet

Fixes #
Docblocks only, to please IDEs.
A couple of places `DateTime -> \WC_DateTime`. Others - just `\`

2021-03-16 04:37 UTC, adrianduffell requested changes
@tivnet Thanks for contributing this! Overall it looks good.

 I think ideally we should use [`\DateTimeInterface`](https://www.php.net/manual/en/class.datetimeinterface.php) for all of these return types. It would provide flexibility to change the internal date implementation in the future. Does this work ok in your IDE?

2021-03-16 12:56 UTC, tivnet commented
@adrianduffell 

> Does this work ok in your IDE?

In PhpStorm it works fine:

![image](https://user-images.githubusercontent.com/1696330/111311943-2a89e180-8635-11eb-8e59-f797d0ecc256.png)

Cannot say anything about other IDEs.

2021-03-16 23:00 UTC, adrianduffell commented
> In PhpStorm, `@return \DateTimeInterface` works fine:

@tivnet Thanks, let's go ahead with changing it to `\DateTimeInterface` and then I think this will be good to merge 🙂

2021-03-17 12:22 UTC, tivnet commented
@adrianduffell Done.

2021-03-19 03:07 UTC, adrianduffell requested changes
Hi @tivnet,

Thanks for making the `\DateTimeInterface` change. However it looks like some other changes came along with it compared to your original commit. I'm guessing it was caused by auto formatting on save. I've highlighted some of it in the code comments.

Are you able to remove these?

Thank you!

2021-03-19 03:07 UTC, adrianduffell commented on src/API/Reports/TimeInterval.php
> +			$hours_offset_timestamp--;
Let's keep the space before `--`

2021-03-19 03:07 UTC, adrianduffell commented on src/API/Reports/TimeInterval.php
> +	 *
A new line was added here.

2021-03-19 03:07 UTC, adrianduffell commented on src/API/Reports/TimeInterval.php
> +
Let's remove the new lines that were added.

2021-03-19 03:07 UTC, adrianduffell commented on src/API/Reports/TimeInterval.php
> +	 * @noinspection PhpUnusedParameterInspection
Let's remove the @noinspection tag

2021-03-19 12:51 UTC, tivnet commented
@adrianduffell I changed the IDE settings... Now it removed more blanks :)

2021-03-24 01:58 UTC, adrianduffell commented
> @adrianduffell I changed the IDE settings... Now it removed more blanks :)

Thanks @tivnet , the removal of the blank lines in the code is a problem too 😅 . Ideally this PR would just be making docblock changes.

2021-03-24 02:29 UTC, closed without merging

2021-03-24 02:30 UTC, tivnet commented
@adrianduffell Never mind :)