Adding typescript resolver to fix linting issues with imports
woocommerce/wc-admin pull request #6624
Opened 2021-03-18 22:09 UTC by joelclimbsthings

no-changelog

Just a quick add of a missing dependency for the typescript resolver. This was missing in a recent PR that changed our Eslint config to use the typescript resolver, the result being linting errors for all of our imports:

![image](https://user-images.githubusercontent.com/444632/111703853-7b4b3700-87fb-11eb-8f10-1a4c0a3f869c.png)

### Testing instructions

-   Checkout branch and run `npm install`
-   Open file in editor such as [this one](https://github.com/woocommerce/woocommerce-admin/blob/cda3b39d082624385a885132b2879db5d3685848/client/wp-admin-scripts/beta-features-tracking-modal/container.js#L0-L1) (I'm using vscode) and ensure that _most_ of the imports do **not** have a linting error. Currently some wordpress packages will still have unresolvable imports.

2021-03-18 23:19 UTC, samueljseay commented
@joelclimbsthings I dunno if its expected but the problem was already there as a warning for quite a while which is why in our original eslint these were set as warnings. I will look at trying to fix this at some point though.

2021-03-18 23:20 UTC, samueljseay requested changes
This looks great, it just needs to be changed to a dev dependency.

2021-03-19 02:28 UTC, joelclimbsthings commented
Ah, good catch @samueljseay . Seems I was typing in `yarn` again, and `--dev` doesn't work with npm 💥 . Just changed.

2021-03-22 22:49 UTC, samueljseay approved these changes

2021-03-23 21:57 UTC, merged