Add IE and NZ to the selective bundle install list
woocommerce/wc-admin pull request #6649
Opened 2021-03-23 17:04 UTC by louwie17

Fixes #6646 

Add New Zealand and Ireland to the selective bundle install list, these where missed in the original PR: #6508 

### Screenshots

<img width="764" alt="Screen Shot 2021-03-23 at 1 56 37 PM" src="https://user-images.githubusercontent.com/2240960/112186362-cf7d5f00-8bdf-11eb-9625-ca2399457a75.png">

### Detailed test instructions:

- Start a new Woo store and go to **WooCommerce > Home** to start the onboarding wizard
- Fill in an address with the country set to **New Zealand — Northland** (try a second time with **Ireland — Carlow**)
- You can select what every industry and product type for the next two windows or select (**Fashion, apparel, and accessories**, and **Physical products**)
- On the business details tab it should just show the dropdowns, and show a **Free features** tab at the top (disabled at first)
- Fill out the dropdowns and click continue
- It should show the free features tab, click the expansion button, **WooCommerce payments** should be listed as part of the free features.
- Keeping WooCommerce payments selected, finish the onboarding
- Check your installed plugins, WooCommerce payments should be installed.

2021-03-23 21:49 UTC, samueljseay requested changes
Looks good, I think we just need to remove testing instructions for this one.

2021-03-23 21:49 UTC, samueljseay commented on TESTING-INSTRUCTIONS.md
> +### Add New Zealand and Ireland to the selective bundle option #6649
I think this isn't critical enough to get testing by global step.

2021-03-23 21:51 UTC, samueljseay approved these changes
I should have pre-approved 😃 just needs testing instructions removed.

2021-03-24 12:30 UTC, merged

2021-03-29 10:03 UTC, adrianduffell commented
This has now also been cherry-picked to 2.1.4 in ccf231b.