Analytics: Add toggle to disable UI features
woocommerce/wc-admin pull request #7168
Opened 2021-06-11 09:54 UTC by psealock

Add a Feature toggle for Analytics. This PR is only responsible for disabling UI portions of the Feature.

### Screenshots

### Detailed test instructions:

-   Ex: Open page `url`
-   Click XYZ…

2021-06-17 15:27 UTC, jeffstieler requested changes

2021-06-17 15:27 UTC, jeffstieler commented on client/layout/controller.js
> +	} );
This change should be reverted, no? The Customers menu item isn't rendered in the legacy menu, but is in the new navigation - where it leads to a broken Customers report (when the analytics feature is disabled).

2021-06-17 15:27 UTC, jeffstieler commented on src/Features/Navigation/CoreMenu.php
> +use Automattic\WooCommerce\Admin\Features\Analytics;
This appears to be unnecessary.

2021-06-18 00:05 UTC, psealock commented
Thanks for the review @jeffstieler 

I reverted the change to the controller so Customers is behind the analytics flag and amended the new Navigation to reflect the same. This brings up a good question, should Customers have its own flag as well? I will follow up on this question because I don't know how integrated the two features are. I think some advanced filters query analytics look up tables, but will double check.

2021-06-18 12:31 UTC, jeffstieler commented
> This brings up a good question, should Customers have its own flag as well? I will follow up on this question because I don't know how integrated the two features are.

IIRC, guest customer syncing is part of the Orders sync, so that would need to get separated if were to give Customers its own feature flag.

2021-06-18 14:38 UTC, jeffstieler approved these changes
This is testing well for me and the code looks good. One question about the class existence check, but that's not a blocker for merge.

Maybe as a follow up we could add a catch-all route as a sort of 404 page.

2021-06-23 01:38 UTC, psealock commented on src/Features/Navigation/CoreMenu.php
> +		if ( class_exists( '\Automattic\WooCommerce\Admin\Features\Analytics' ) && Features::is_enabled( 'analytics' ) ) {
You are right, it won't be needed. The feature check is sufficient enough for the operation performed in the if statement. Fixed in https://github.com/woocommerce/woocommerce-admin/pull/7168/commits/74cf2b7ab9e1b17bbc61da698dd8075f9971f676

2021-06-23 01:50 UTC, merged

2021-08-18 16:06 UTC, ArneSaknussemm commented
Great! thank you. Can you do this for Marketing features also?