Localize payment gateway suggestions on wccom
woocommerce/wc-admin pull request #7217
Opened 2021-06-21 20:30 UTC by joshuatf

Removes the `locales` property in payment gateway suggestion specs in favor of localizing using i18n on WCCOM.

NOTE- Wait for WCCOM PR approval before merging

### Detailed test instructions:

Test using the WCCOM config PR - https://github.com/Automattic/woocommerce.com/pull/10565

2021-06-23 00:07 UTC, joelclimbsthings commented
Hey @joshuatf , I've been working on getting a dev setup of woocommerce.com up and running to review this PR, but it's been slow going. It seems to have some issues running along-side Local, and it looks like some of the setup scripts expect a mac environment.

That said, I _do_ have it running, but I'm getting a few scattered issues like this when I try to install wc-pay through the payment task:

![image](https://user-images.githubusercontent.com/444632/123015014-490e2000-d37c-11eb-89fe-48d0b1f56832.png)

I don't believe that stems from anything in the PR, but if you have any tips let me know.

I had a couple comments on the config in the companion PR as well, and I'll continue to look at this tomorrow.

2021-06-23 17:25 UTC, joelclimbsthings commented
Disregard the above @joshuatf . So far testing is looking good. We may want to rebase this to include recent bug fixes, though, since I can't validate some of that behavior otherwise.

2021-06-23 17:32 UTC, joshuatf commented
Hey @joelclimbsthings - just pushed again with the latest rebase on `main`.

2021-06-23 21:02 UTC, joelclimbsthings commented
Thanks @joshuatf , after parsing through the gateways I came across a few that weren't showing up at all due to using the obsolete `key` prop instead of `id`, and I commented on the WCCOM PR. Just wanted to mention here that we had the same issue with the defaults, which I've put up a [quick PR](https://github.com/woocommerce/woocommerce-admin/pull/7229) for (so you don't need to bother here).

2021-06-23 22:47 UTC, joelclimbsthings requested changes
Hey @joshuatf, well done here. I used the opportunity to smoke test all of the gateways and found a few unrelated bugs (and issued PRs), but the functionality here seems to work. 

I'm not entirely certain how to test the locale. I added `locale=es_ES` to the query string on the request, but didn't notice any changes in the response. Would this just be due to lack of translations at this stage?

2021-06-24 14:03 UTC, joshuatf commented
> Just wanted to mention here that we had the same issue with the defaults, which I've put up a quick PR for (so you don't need to bother here).

Thanks, @joelclimbsthings!  Those must have been reverted to `key` during merge conflicts at some point.

>I'm not entirely certain how to test the locale. I added locale=es_ES to the query string on the request, but didn't notice any changes in the response. Would this just be due to lack of translations at this stage?

Correct, there are no translations at this point, but you could add them if you wanted to test.  The easier way may just to dump the locale on wccom to check.  In the wccom PR:

>Check that passing _locale for this endpoint updates the returned value from get_locale() - this could use a sanity check.

2021-06-28 21:45 UTC, joelclimbsthings commented
> Check that passing _locale for this endpoint updates the returned value from get_locale() - this could use a sanity check.

Perfect, just did so and it worked as expected 👍🏻 . LGTM and approving, although it seems we won't be merging this quite yet as we want for the WCCOM PR.

2021-06-28 21:45 UTC, joelclimbsthings approved these changes

2021-07-05 21:50 UTC, joshuatf commented
WCCOM PR is now merged!  Merging this one in.

2021-07-05 21:50 UTC, merged