Add WC Pay in person text
woocommerce/wc-admin pull request #7830
Opened 2021-10-20 19:51 UTC by joshuatf

Fixes (part of) #7719 

Updates the WC Pay card text and button alignment.

### Screenshots

#### Before
<img width="224" alt="Screen Shot 2021-10-20 at 3 39 14 PM" src="https://user-images.githubusercontent.com/10561050/138161955-d121b5c3-790e-4576-82be-51afa4c30082.png">

#### After

<img width="266" alt="Screen Shot 2021-10-20 at 3 46 09 PM" src="https://user-images.githubusercontent.com/10561050/138161948-6ab40791-fdf0-44c7-a6ca-c2acf3c3f09f.png">

<img width="763" alt="Screen Shot 2021-10-21 at 4 13 40 PM" src="https://user-images.githubusercontent.com/10561050/138350617-7e9af501-d1e1-467f-9379-e2f92bad4534.png">

### Detailed test instructions:

1. Set your store location to US
2. Set your store to NOT allow marketplace suggestions
3. Delete the `woocommerce_admin_payment_gateway_suggestions_specs` option if it exists
2. Delete the `woocommerce_onboarding_profile` option (or don't select WC Pay in the free extensions step)
3. Deactivate WC Pay if active
3. Visit the payments task
4. Note the copy change
5. Activate WC Pay
6. Note the "Finish Setup" button aligment
7. Set your store to a non-US location and note the text
8. Repeat this process with marketplace suggestion on using this PR - https://github.com/Automattic/woocommerce.com/pull/11555

2021-10-22 15:14 UTC, louwie17 approved these changes
Nice work @joshuatf, this PR tested well. I left one suggestion, but that didn't seem to affect testing.

2021-10-29 01:29 UTC, mattsherman requested changes
When testing this with this branch (WCA `2.9.0-dev`) and WooCommerce `5.9.0-beta.1`, I was not getting the correct copy.

I think we should be comparing to `woocommerce-admin` `2.9.0-dev` and `woocommerce` `5.10.0-dev`. When I made those changes locally and tested, things worked as I would expect.

I was not able to figure out how to get the "Finish setup" button to appear. I'm not sure if there is something wrong with my setup, or something wrong with the code/testing instructions.

2021-11-01 17:42 UTC, mattsherman commented
> Thanks for the review, @mattsherman!
> 
> > I think we should be comparing to woocommerce-admin 2.9.0-dev and woocommerce 5.10.0-dev. When I made those changes locally and tested, things worked as I would expect.
> 
> That does make this work in a local testing environment, but I don't think we'd ever need those suggestions in the development versions since this only affects releases.

If we do not compare to against the `-dev` version numbers, any pre-release will not work as we expect, as they compare as "less than" the final release version. 

> > Why aren't the version rules necessary here?
> 
> Because we're checking for older versions of WooCommerce Admin and the release this code is included in will always be newer versions than those checks. The only reason to keep them here is in case they get copy-pasted to the WCCOM endpoint. I'm in favor with keeping them in sync in case that does happen.

That makes sense.

2021-11-01 19:55 UTC, joshuatf commented
>If we do not compare to against the -dev version numbers, any pre-release will not work as we expect, as they compare as "less than" the final release version.

Ah, good point @mattsherman.  Updated in https://github.com/woocommerce/woocommerce-admin/pull/7830/commits/1a07d6c7436f9803e40aa1f7294ed13ec7214fa3.

2021-11-01 21:49 UTC, mattsherman commented
> > If we do not compare to against the -dev version numbers, any pre-release will not work as we expect, as they compare as "less than" the final release version.
> 
> Ah, good point @mattsherman. Updated in [1a07d6c](https://github.com/woocommerce/woocommerce-admin/commit/1a07d6c7436f9803e40aa1f7294ed13ec7214fa3).

Thanks. I believe we should do the same with the WC versions, as otherwise, when WCA gets included in the next WC core pre-release, things will not work as expected.

Also, thinking about it more... I believe the next WC release is actually going to be `6.0`. But, keeping the checks as `5.10.0-dev` would accommodate either should versioning plans change.

2021-11-01 22:06 UTC, joshuatf commented
Good call, @mattsherman.  Updated in https://github.com/woocommerce/woocommerce-admin/pull/7830/commits/24aac8bffc7983f5b1af14587d48c60aec20b2d7.

2021-11-01 22:30 UTC, mattsherman approved these changes
Re-tested with the latest version number changes. Thanks for updating this, @joshuatf. Works as expected now!

2021-11-02 13:03 UTC, merged