Update dependencies to support react 17
woocommerce/wc-admin pull request #8305
Opened 2022-02-14 03:37 UTC by chihsuan

2022-02-15 08:28 UTC, rjchow approved these changes
Nice work! Appreciate this very laborious and often thankless work.
Automated tests and smoke testing went well, almost all the changes look fine.

I went over the changelogs of every package that was update and the only things that stood out were:
- Most of them had breaking changes of IE11 deprecation and Node.JS LTS 12 as the minimum version - wonder if we should add this to our own changelog?
- @wordpress/components deprecated some props (isPrimary, isSecondary, isTertiary, isLink) in `<Button>` and we use those props, so we should probably make a separate issue to fix them before they completely remove support. https://github.com/WordPress/gutenberg/blob/81e8e0f7c999df3cc43ef97cb2913779c0190eff/packages/components/CHANGELOG.md#deprecation-1

2022-02-15 09:31 UTC, chihsuan commented
>     * Most of them had breaking changes of IE11 deprecation and Node.JS LTS 12 as the minimum version - wonder if we should add this to our own changelog?
> 
>     * @wordpress/components deprecated some props (isPrimary, isSecondary, isTertiary, isLink) in `<Button>` and we use those props, so we should probably make a separate issue to fix them before they completely remove support. https://github.com/WordPress/gutenberg/blob/81e8e0f7c999df3cc43ef97cb2913779c0190eff/packages/components/CHANGELOG.md#deprecation-1

@rjchow Thanks for spotting them. I've add IE11 deprecation note to changelogs in  bd4a659f791e3a618bdca99ce3b8bb8db4f0690e. I think our minimum Node JS version is already 12 as defined in the package.json.

Also created a follow-up issue https://github.com/woocommerce/woocommerce-admin/issues/8313 for `<Button>`

2022-02-17 07:03 UTC, ilyasfoo requested changes
Thanks so much for the work here, @chihsuan! It's super neat that you've also properly separated the changes into different commits, definitely helped with reviewing there.

I've found an issue with `createNotice` changes. Everything else is looking good so far!

2022-02-17 08:49 UTC, chihsuan commented on client/homescreen/activity-panel/reviews/index.js
> +									callback: () => {
Good catch. I think you're right. It's still used `onClick`.  I found the `callback` from typescript warnings and `@types/wordpress__notices`.


![Screen Shot 2022-02-17 at 16 45 44](https://user-images.githubusercontent.com/4344253/154438792-ea2cae18-d4f8-44ce-8d8e-c966e0b3de87.png)
![Screen Shot 2022-02-17 at 16 45 53](https://user-images.githubusercontent.com/4344253/154438802-20f8a305-ec9e-4e3f-beae-915deb47034b.png)
.

2022-02-17 08:50 UTC, chihsuan commented on client/homescreen/activity-panel/reviews/index.js
> +									callback: () => {
https://www.npmjs.com/package/@types/wordpress__notices

The last published is a year ago. : (

2022-02-17 08:56 UTC, chihsuan commented on client/homescreen/activity-panel/reviews/index.js
> +									callback: () => {
Let me drop this commit https://github.com/woocommerce/woocommerce-admin/commit/4666b8f0ca5300665db08fbe4d2ccdfe8fc6f0a9 and possibly fill an issue on Gutenberg.

2022-02-17 09:26 UTC, chihsuan commented on client/homescreen/activity-panel/reviews/index.js
> +									callback: () => {
I've reverted the changes and confirmed they actually changed from `callback` to `onClick` (https://github.com/WordPress/gutenberg/pull/17206), but [didn't update the file in DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/wordpress__notices/index.d.ts#L32).

2022-02-17 11:17 UTC, ilyasfoo commented on client/homescreen/activity-panel/reviews/index.js
> +									callback: () => {
Ah, I see. Yeah it seems that'll need an update

2022-02-18 05:34 UTC, chihsuan commented on client/homescreen/activity-panel/reviews/index.js
> +									callback: () => {
Update: I've raised a discussion https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/58850 based on https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377.

2022-02-18 09:08 UTC, ilyasfoo approved these changes
I confirm that `createNotice` is working again. LGTM!

2022-02-18 09:15 UTC, adrianduffell approved these changes
Smoke test went well for me! Nice job on this @chihsuan 👍

2022-02-18 09:43 UTC, chihsuan commented on client/homescreen/activity-panel/reviews/index.js
> +									callback: () => {
I tagged the other maintainers from `@types/wordpress__components` 🥲

2022-02-21 02:34 UTC, merged