Add context arg to Notes\DataStore::get_notes().
woocommerce/wc-admin pull request #8386
Opened 2022-02-27 18:23 UTC by jacob-sewell

Fixes #8385 

(See the issue for much more discussion.)

This simply adds `'context' => 'global'` to the default arguments array for `Admin\Notes\DataStore::get_notes()` so that it can be used by third party developers to avoid applying custom `woocommerce_note_where_clauses` changes when not needed.

### Detailed test instructions:

There should be no change in behavior, but you can use a custom plugin to add a filter function to `'woocommerce_note_where_clauses'` and verify that it receives `'context' => 'global'` in its args array. For extra points you can call `get_notes()` yourself with a different value for `'context'` and verify that it comes through as expected.

2022-03-03 15:34 UTC, louwie17 requested changes
I originally thought this change was far from necessary, but after some digging and pulling a few examples (I couldn't find many), I think this might be beneficial along with the change in #8387.
I do have suggestion in terms of usage, I think instead of adding the context as an arg, I think we should create an extra parameter for the `get_notes` function called context and default to `global`.
We do the same when passing it into the `woocommerce_note_where_clauses` filter, adding context as a third parameter.
I think this help will prevent confusion, and would also help increase adoption as it will be more explicit.
Here is an example of Wordpress making use of $context in one of the filters - https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-plugins-list-table.php#L908-L912

2022-03-03 16:12 UTC, joshuatf reviewed
Just popping in here to say that this is a fantastic addition.  More discussion here - p91TBi-7kt-p2 as to why we'll need this.

One thing that may be worth discussing prior to adding this is how we derive and set context.  Using enums/integers for context would be a bit more ideal for better indexing and searching, but we'd need a helper to determine context and some filters for extensibility.

2022-03-15 23:09 UTC, jacob-sewell commented
> Just popping in here to say that this is a fantastic addition. More discussion here - p91TBi-7kt-p2 as to why we'll need this.

The approach contained here is essentially just a shibboleth that lets third-party code that messes with note filters turn itself off when the call is not coming from their own code. I'm not sure whether it can easily be extended to cover this case. Perhaps with the addition of `lookup_notes()` we can consider adding a global filter that screens out notes that shouldn't be shown on mobile when the query is for display? Does the backend know what kind of frontend is making requests of it?

2022-03-16 14:42 UTC, louwie17 approved these changes
Pre-approving this, thanks for the changes @jacob-sewell, I think this is great!
There was just one missing param comment, the one for the filter, if you could add that prior to merging :)

2022-03-16 14:42 UTC, louwie17 commented on src/Notes/DataStore.php
>  		 * @param array  $args          The original arguments for the request.
An update for the filter param comment would be great as well :)

2022-03-25 07:44 UTC, ilyasfoo commented
Hey, @jacob-sewell! Since it's past The Merge, I don't think we should merge any more codes in this repo unless it's cherry-picked into WCA 3.3 branch. Otherwise, will it be okay for you to recreate all the changes to the core repo instead?

2022-04-08 17:38 UTC, mattsherman commented
@jacob-sewell We really should move this PR to core and get this wrapped up... I'll put this back in our backlog to tackle in the upcoming cycle.

2022-04-13 19:02 UTC, jacob-sewell commented
Closing as obsolete (post-merge equivalent PR in woocommerce/woocommerce [here](https://github.com/woocommerce/woocommerce/pull/32574)).

2022-04-13 19:02 UTC, closed without merging