Create lookup_notes method to bypass woocommerce_note_where_clauses filter.
woocommerce/wc-admin pull request #8387
Opened 2022-02-28 03:21 UTC by jacob-sewell

Add args_to_where_clauses() and lookup_notes() methods to Admin\Notes\DataStore.

For use by internal code to bypass woocommerce_note_where_clauses filter.

Fixes #8385 (See the Issue for much more discussion of the problem we'd like to solve and whether this is the way to solve it.)

This is one possible way to avoid potentially-expensive `get_notes()` calls in internal note code. The new method `lookup_notes()` works the same as the existing `get_notes()` but bypasses the woocommerce_note_where_clauses filter and omits paging. (The logic in `get_notes_where_clauses()` related to argument sanitization is moved into the new method `args_to_where_clauses()` and the old where clauses method simply adds application of the filter. The new filterless method is called by `lookup_notes()`.)

2022-03-03 13:33 UTC, louwie17 requested changes
> I will say that I don't love having two similarly named methods in the Notes DataStore with the same signature, but the more I think about it the less I think our internal code should be using get_notes() at all. Its results are paged! It shouldn't be used for anything but display.

I agree! I think these changes look good from my perspective, nice and simple!
Given we are adding a new function with different functionality I think this would be a great opportunity to add some unit tests to cover the new function.

Also cc'ing @octaedro given he is working on making Notes internal, I wonder if this function should be moved to a `Internal` class if we have a helper function of some sort, or maybe we want to move some of these functions out into a separate Internal class? (not something that should be part of this PR, but be considered for the Internal work).

2022-03-03 16:14 UTC, jacob-sewell commented
> I think this would be a great opportunity to add some unit tests to cover the new function.

That's definitely true. I'll add that to my queue.

2022-03-15 02:37 UTC, jacob-sewell commented
Finally got this test to a place where I'm happy with it. I haven't compared to main yet to see whether there are gnarly conflicts.

2022-03-15 17:01 UTC, louwie17 requested changes
Thanks for adding the test @jacob-sewell, I just left one suggestion about cleanup and a tiny addition to a comment to help clarify the condition.

2022-03-15 17:20 UTC, jacob-sewell commented on tests/notes/class-wc-tests-notes-data-store.php
> +		$this->assertEquals( $lookup_note_zero->get_id(), $get_note_zero->get_id() );
Do we want to truncate the tables or just delete by source? It looks like the notes we create all have an appropriate source param.

2022-03-15 17:32 UTC, louwie17 commented on tests/notes/class-wc-tests-notes-data-store.php
> +		$this->assertEquals( $lookup_note_zero->get_id(), $get_note_zero->get_id() );
Either one works, source seems like a good option given most tests make use of PHPUNIT_TEST

2022-03-15 17:47 UTC, jacob-sewell commented on tests/notes/class-wc-tests-notes-data-store.php
> +		$this->assertEquals( $lookup_note_zero->get_id(), $get_note_zero->get_id() );
I just pushed a commit that adds source to all the Notes created by this test that didn't already have it, and another that adds a tearDown method that deletes notes and actions by note source.

2022-03-15 19:15 UTC, louwie17 approved these changes
Thanks for all the updates @jacob-sewell, things look great, this is ready to 🚢 

Also as mentioned in Slack sorry for adding some extra unnecessary work with deleting the created notes as `parent::tearDown()` seems to be doing that.

2022-03-15 19:23 UTC, jacob-sewell commented
> Also as mentioned in Slack sorry for adding some extra unnecessary work with deleting the created notes as `parent::tearDown()` seems to be doing that.

Yep. I'm going to go ahead and leave it in just in case the other behavior changes.

2022-03-15 19:24 UTC, merged