Activity Panel: Inbox: Filter update and error notes out of the inbox
woocommerce/wc-admin pull request #893
Opened 2018-11-19 23:52 UTC by allendav

Fixes #722

Filters the inbox so that error and update notes do NOT appear. (They belong in the as-yet-not-implemented Store Alerts component.)

### Detailed test instructions:

- Use the https://github.com/Automattic/wc-admin-notes-test-bench plugin to add notes of all four types.
- Navigate to wp-admin > WooCommerce > Dashboard > Inbox
- Make sure the error and update notes do NOT appear
- Make sure the info and warning notes DO appear
- Run the phpunit tests and make sure they pass

2018-11-20 22:35 UTC, psealock commented
I'm not sure if I have the notes test bench plugin working correctly. Should I be seeing at least one warning message?

![screen shot 2018-11-21 at 11 26 02 am](https://user-images.githubusercontent.com/1922453/48807101-53f61380-ed81-11e8-96a0-7ba79e1d9506.png)

I do see the `type: info,warning` query added to the request, however

2018-11-26 17:22 UTC, claudiosanches commented on includes/api/class-wc-admin-rest-admin-notes-controller.php
> +		$type = sanitize_text_field( trim( $type ) );
`sanitize_text_field()` already trim empty spaces.

```bash
$ wp shell
wp> sanitize_text_field( '  text   ' )
=> string(4) "text"
wp> 
```

2018-12-03 10:14 UTC, joshuatf requested changes
@allendav This is testing well for me in the dashboard and only info/warnings are showing up 👍 

The phpunit tests are failing though:
```
1) WC_Tests_API_Admin_Notes::test_get_warning_notes
Failed asserting that 2 matches expected 1.
```
It doesn't look like the types are passed to `get_notes()` so `$escaped_where_types` is empty.  Do we want to set these by default to only show info/warning in the API or change the tests to assert a count of 2?

2018-12-04 01:01 UTC, allendav commented
@joshuatf wrote:

> It doesn't look like the types are passed to get_notes() so $escaped_where_types is empty

Thanks for catching that - will fix asap

2018-12-05 21:18 UTC, jeffstieler commented
This is ready for another review.

2018-12-07 00:40 UTC, timmyc commented
@joshuatf could you give this one another 👀 ?

2018-12-07 02:21 UTC, joshuatf approved these changes

2018-12-11 01:00 UTC, merged